### ISSUE TITLE
Cannot use debugging

### ISSUE THREAD

**Issue by ghost** [phoityne/phoityne-vscode#40]
I am getting the following error when using debugging mode:

[HASKELL][ERROR] not found "haskell-debug-adapter" configurations. 
![screenshot from 2019-02-08 23-58-36](https://user-images.githubusercontent.com/2532888/52518304-90594300-2bfd-11e9-9c79-e9f1981aabd3.png)

**Comment by phoityne** [comment]
Could you let me know that there is a launch.json in the .vscode folder ?
It will be created by pressing "F5", at the first time.

From above dialog, means that phoityne can not find haskell configuration section in the launch.json.

**Comment by ghost** [comment]
Thanks for your response. There is no launch.json file in the folder. It does not get created when I call F5 on the file. Do I need to manually create the file? Is there an example file somewhere?

**Comment by phoityne** [comment]
I think it will be created by vscode automatically.
Did you open folder from vscode file menu ?

VSCode also creates the ".vscode" folder in that project folder.

**Comment by ghost** [comment]
Thanks for your pointer. The .vscode folder and launch.json was not created automatically, I used the following link to create the launch.json manually:

https://code.visualstudio.com/docs/editor/debugging#_launch-configurations

Thanks again for the wonderful plugin 👍

**Comment by gc-av** [comment]
Hey @phoityne,
Asking for help with this 3 years later, because I have the same issue and don't know what else to do.

<img width="565" alt="image" src="https://user-images.githubusercontent.com/56302061/208288830-181403a9-b672-4885-8f7a-c85be8d9d5bf.png">

> Could you let me know that there is a launch.json in the .vscode folder ?
It will be created by pressing "F5", at the first time.

There was no launch.json, not even when I pressed F5. 

So I did what @Vinodh89 suggested and created one following the instructions from here:

> https://code.visualstudio.com/docs/editor/debugging#_launch-configurations

<img width="192" alt="image" src="https://user-images.githubusercontent.com/56302061/208289315-79b4bd64-a629-4b11-b1fa-10131894c057.png">

<details>

<summary>My launch.json file</summary>

Note that `"name": "haskell(stack)"` and `"name": "haskell(cabal)"` were auto-generated. As neither corresponded to my setup, I added the entry `"name": "haskell(mine)"`.

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "ghc",
      "request": "launch",
      "name": "haskell(stack)",
      "internalConsoleOptions": "openOnSessionStart",
      "workspace": "${workspaceFolder}",
      "startup": "${workspaceFolder}/test/Spec.hs",
      "startupFunc": "",
      "startupArgs": "",
      "stopOnEntry": false,
      "mainArgs": "",
      "ghciPrompt": "H>>= ",
      "ghciInitialPrompt": "Prelude>",
      "ghciCmd": "stack ghci --test --no-load --no-build --main-is TARGET",
      "ghciEnv": {},
      "logFile": "${workspaceFolder}/.vscode/phoityne.log",
      "logLevel": "WARNING",
      "forceInspect": false
    },
    {
      "type": "ghc",
      "request": "launch",
      "name": "haskell(cabal)",
      "internalConsoleOptions": "openOnSessionStart",
      "workspace": "${workspaceFolder}",
      "startup": "${workspaceFolder}/Main.hs",
      "startupFunc": "",
      "startupArgs": "",
      "stopOnEntry": false,
      "mainArgs": "",
      "ghciPrompt": "H>>= ",
      "ghciInitialPrompt": "Prelude>",
      "ghciCmd": "cabal exec -- ghci-dap --interactive -i -i${workspaceFolder}",
      "ghciEnv": {},
      "logFile": "${workspaceFolder}/.vscode/phoityne.log",
      "logLevel": "WARNING",
      "forceInspect": false
    },
    {
      "type": "ghc",
      "request": "launch",
      "name": "haskell(mine)",
      "internalConsoleOptions": "openOnSessionStart",
      "workspace": "${workspaceFolder}",
      "startup": "${workspaceFolder}/${file}",
      "startupFunc": "main",
      "startupArgs": "",
      "stopOnEntry": false,
      "mainArgs": "",
      "ghciPrompt": "H>>= ",
      "ghciInitialPrompt": "Prelude>",
      "ghciCmd": "cabal exec -- ghci-dap --interactive -i -i${workspaceFolder}",
      "ghciEnv": {},
      "logFile": "${workspaceFolder}/.vscode/phoityne.log",
      "logLevel": "WARNING",
      "forceInspect": false
    }
  ]
}
```
</details>

I tried all 3 environments(?) defined in the file, but nothing worked. 

**Some other (perhaps irrelevant) notes**
- I also got a warning about my cradle being none. So I followed the instructions from [here](https://hackage.haskell.org/package/hie-bios#stack). That warning disappeared, but no progress in terms of getting the debugger to work.
- I have also tried restarting VSCode, restarting my computer, and cleaning and rebuilding Stack. All to no avail.

I'm a bit of a Haskell newbie, so I don't know what else I can try. Help, please?

Either way, thank you for the extension!
